name: Clojure CI + WAR Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Leiningen
        run: |
          curl https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein > lein
          chmod +x lein
          sudo mv lein /usr/local/bin/

      - name: Install dependencies
        run: lein deps

      - name: Run tests
        run: lein test

      - name: Build WAR
        run: lein ring uberwar  # ou o comando específico do seu projeto para gerar .war

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-webapp-war
          path: target/*.war
