name: Clojure WAR CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Leiningen
        run: |
          curl https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein > lein
          chmod +x lein
          sudo mv lein /usr/local/bin/

      - name: Install dependencies
        run: lein deps

      - name: Run tests
        run: lein test

      - name: Build WAR
        run: lein ring war

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: war-package
          path: sisrh.war  # ou o nome que você definiu no project.clj
