name: Java Maven Build and Deploy

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - "*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build com Maven
        run: mvn clean package

      - name: Verificar arquivos gerados no target
        run: ls -lah target

      - name: Preparar diretório de deploy
        run: |
          mkdir -p deploy
          # Verificando se o arquivo .war está presente em target
          if [ -f target/sisrh.war ]; then
            cp target/sisrh.war deploy/
          else
            echo "Erro: O arquivo sisrh.war não foi encontrado."
            exit 1
          fi

      - name: Configurar git para o deploy
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Criar ou atualizar branch deploy
        run: |
          git fetch origin
          if git ls-remote --exit-code --heads origin deploy; then
            git checkout deploy
          else
            git checkout --orphan deploy
          fi

      - name: Deploy WAR para branch deploy
        run: |
          # Limpa a pasta, caso haja conteúdo residual
          rm -rf *
          # Copia o WAR da pasta de deploy
          cp deploy/sisrh.war .
          
          # Adiciona, comita e faz push do WAR
          git add *.war
          git commit -m "Deploy automático do WAR em $(date +'%Y-%m-%d %H:%M:%S')" || echo "Nada para commitar"
          git push origin deploy --force
