name: Testes Unitários PR

on:
  pull_request:
    branches:
      - master  # Altere para "master" se seu branch principal for master

jobs:
  testar:
    name: Executar testes com Maven
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Rodar testes com Maven
        run: mvn clean test
